/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author isaco
 */
public class Combate extends javax.swing.JFrame {
    private String user;
    private String cpu;
    private String[] userNO={"1"};
    private int vidaMaxUser;
    private String[] cpuNO={"12"};
    private int vidaMaxCPU;
    
    
    public Combate(String user, String cpu) {  //despues agregar las cosas
        this.user = user;
        this.cpu = cpu;
        
        
        setTitle("Combate  "+user+" VS "+cpu);  
        
        
        //fotos pokemon
        ImagePokemon(userNO, 80,110);
        ImagePokemon(cpuNO, 490,20);
        initComponents();
        add(LifeBase(), BorderLayout.CENTER);
        getContentPane().add(Background(),BorderLayout.CENTER);
        BarrasVidas(user, userNO, vidaMaxUser, cpu, cpuNO, vidaMaxCPU);
        setLocationRelativeTo(null);
        
       //Batalla
       
     
    }
      
       public void ImagePokemon (String[] selected_pokemon, int x, int y ){

           if(selected_pokemon[0].length()== 1)
        {
           selected_pokemon[0]= "00"+selected_pokemon[0];
        }
        else if(selected_pokemon[0].length()== 2)
        {
           selected_pokemon[0]= "0"+selected_pokemon[0];
        }
           String num = selected_pokemon[0];
           
        ImageIcon Img = new ImageIcon("src/main/java/poo/assets/"+num+ ".png"); 
        Image image = Img.getImage();
        Image newimg = image.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
        Img = new ImageIcon(newimg);
        JLabel IMG = new JLabel (Img);
        IMG.setSize(150,150);     
        IMG.setOpaque(false);
        add(IMG);
        IMG.setLocation(x, y);  
        }
       public void BarrasVidas (String user, String[] userNO, int vidaMaxUser, String cpu, String[] cpuNO, int vidaMaxCPU){
       //lifeUser 
       nameUser.setText(user);
       numUser.setText("Lv"+userNO[0]);
       lifeUser.setMaximum(vidaMaxUser);
       lifeUser.setMinimum(0);
       lifeUser.setValue(25);
       vidaNum.setText(vidaMaxUser+"/ "+vidaMaxUser);
       
       //lifeCPU 
       nameCPU.setText(cpu);
       numCPU.setText("Lv"+cpuNO[0]);
       lifeCPU.setMaximum(vidaMaxCPU);
       lifeCPU.setMinimum(0);
       lifeCPU.setValue(25);
       }    
       public JLabel LifeBase (){
        ImageIcon life = new ImageIcon("src/main/java/poo/backgroundCombate/lifeBase.png"); 
        JLabel lifeBase = new JLabel (life);
        lifeBase.setSize(720,360);     
        lifeBase.setOpaque(false);  //PROPIEDADES
        return lifeBase;
       }
       public JLabel Background (){
        ImageIcon background = new ImageIcon("src/main/java/poo/backgroundCombate/backgroundCombate.jpg"); 
        JLabel backgroundCombate = new JLabel (background);
        backgroundCombate.setSize(720,360);     //PROPIEDADES
        backgroundCombate.setOpaque(false);  
        return backgroundCombate;
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Action = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Combate = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        lifeUser = new javax.swing.JProgressBar();
        lifeCPU = new javax.swing.JProgressBar();
        numCPU = new javax.swing.JLabel();
        vidaNum = new javax.swing.JLabel();
        nameCPU = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();
        numUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Action.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionActionPerformed(evt);
            }
        });

        Combate.setEditable(false);
        Combate.setColumns(20);
        Combate.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Combate.setRows(5);
        jScrollPane1.setViewportView(Combate);

        jToggleButton1.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Attack!!");
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setMargin(new java.awt.Insets(2, 14, 2, 14));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lifeUser.setBackground(new java.awt.Color(163, 255, 153));
        lifeUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lifeCPU.setBackground(new java.awt.Color(102, 255, 102));
        lifeCPU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        numCPU.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        numCPU.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numCPU.setText("Lv000");
        numCPU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        vidaNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vidaNum.setText("00/ 00");

        nameCPU.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        nameCPU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameCPU.setText("CPU");
        nameCPU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        nameUser.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        nameUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameUser.setText("USER");
        nameUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        numUser.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        numUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numUser.setText("Lv000");
        numUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setText("cpu ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numCPU))
                            .addComponent(lifeCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Action)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vidaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lifeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numUser))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameCPU)
                    .addComponent(numCPU)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(lifeCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameUser)
                    .addComponent(numUser))
                .addGap(6, 6, 6)
                .addComponent(lifeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vidaNum)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    String user = "ahh";
    String cpu = "ahh";
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combate(user, cpu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Action;
    private javax.swing.JTextArea Combate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JProgressBar lifeCPU;
    private javax.swing.JProgressBar lifeUser;
    private javax.swing.JLabel nameCPU;
    private javax.swing.JLabel nameUser;
    private javax.swing.JLabel numCPU;
    private javax.swing.JLabel numUser;
    private javax.swing.JLabel vidaNum;
    // End of variables declaration//GEN-END:variables
}
