/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author isaco
 */
public class CombateSetUp extends javax.swing.JFrame {
    String[] selected_pokemon = {};
    File file = new File("./favorites.csv");
    File list = new File("./pokemon_list.csv");

    boolean enabled = false;
    /**
     * Creates new form CombateSetUp
     */
    public CombateSetUp() {
        setTitle("Set Up");
        initComponents();
        getContentPane().setBackground(Color.blue);
        setLocation(100,100);
        
        //fondo y propiedades 
        ImageIcon background = new ImageIcon("src/main/java/poo/backgroundCombate/backgroundSetCombate.jpg"); 
        JLabel backgroundCombate = new JLabel (background);
        backgroundCombate.setSize(420,570);     //PROPIEDADES
        backgroundCombate.setOpaque(false);  
        
        //agregamos 
        getContentPane().add(backgroundCombate,BorderLayout.CENTER);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PokemonUserRes = new javax.swing.JTextField();
        buscarPokemonUser = new javax.swing.JTextField();
        buscarUserButton = new javax.swing.JButton();
        buscarCpuButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PokemonCpuRes = new javax.swing.JTextField();
        buscarPokemonCpu = new javax.swing.JTextField();
        CombateStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PokemonUserIMG = new javax.swing.JLabel();
        PokemonCpuIMG1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 87, 211));
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Set Up");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Pokemon");

        PokemonUserRes.setEditable(false);
        PokemonUserRes.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        PokemonUserRes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PokemonUserRes.setText("Resultado busqueda");
        PokemonUserRes.setPreferredSize(new java.awt.Dimension(125, 25));

        buscarPokemonUser.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buscarPokemonUser.setText("Pokemon a buscar");
        buscarPokemonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPokemonUserActionPerformed(evt);
            }
        });

        buscarUserButton.setBackground(new java.awt.Color(104, 140, 242));
        buscarUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        buscarUserButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarUserButton.setText("Buscar");
        buscarUserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buscarUserButton.setBorderPainted(false);
        buscarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUserButtonActionPerformed(evt);
            }
        });

        buscarCpuButton.setBackground(new java.awt.Color(104, 140, 242));
        buscarCpuButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        buscarCpuButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarCpuButton.setText("Buscar");
        buscarCpuButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buscarCpuButton.setBorderPainted(false);
        buscarCpuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCpuButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cpu Pokemon");

        PokemonCpuRes.setEditable(false);
        PokemonCpuRes.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        PokemonCpuRes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PokemonCpuRes.setText("Resultado busqueda");
        PokemonCpuRes.setMinimumSize(new java.awt.Dimension(64, 24));
        PokemonCpuRes.setPreferredSize(new java.awt.Dimension(125, 25));

        buscarPokemonCpu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buscarPokemonCpu.setText("Pokemon a buscar");
        buscarPokemonCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPokemonCpuActionPerformed(evt);
            }
        });

        CombateStart.setBackground(new java.awt.Color(255, 153, 153));
        CombateStart.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        CombateStart.setForeground(new java.awt.Color(255, 255, 255));
        CombateStart.setText("FIGHT!");
        CombateStart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CombateStart.setBorderPainted(false);
        CombateStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombateStartActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nombre");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nombre");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 219, 92));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("vs.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(CombateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PokemonUserIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PokemonCpuIMG1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(buscarUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(buscarCpuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buscarPokemonUser, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buscarPokemonCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PokemonCpuRes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PokemonUserRes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(80, 80, 80)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(buscarPokemonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(PokemonUserRes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PokemonUserIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(buscarPokemonCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCpuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PokemonCpuIMG1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PokemonCpuRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(CombateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarPokemonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPokemonUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPokemonUserActionPerformed

    private void buscarPokemonCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPokemonCpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPokemonCpuActionPerformed

    private void CombateStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombateStartActionPerformed
        // TODO add your handling code here:
        new Combate("user","cpu").setVisible(true);
    }//GEN-LAST:event_CombateStartActionPerformed

    private void buscarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUserButtonActionPerformed
        // TODO add your handling code here:
        String search =buscarPokemonUser.getText();
        readFile(search);
 
    }//GEN-LAST:event_buscarUserButtonActionPerformed

    private void buscarCpuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCpuButtonActionPerformed
        // TODO add your handling code here:
             String search =buscarPokemonCpu.getText();
        readFileComplete(search);
    }//GEN-LAST:event_buscarCpuButtonActionPerformed

        public void readFile(String search) {
        try {
            FileReader file_reader = new FileReader(file);
            BufferedReader buffered_reader = new BufferedReader(file_reader);
            String linea = "";
            String Text = "";
            while ((linea = buffered_reader.readLine()) != null) {
                String[] pokemon = linea.split(",");
                if (pokemon[1].contentEquals(search)) {
                    Text = Text + pokemon[1] + "\n";
                    selected_pokemon=pokemon;
                }
            }
             if(Text.equals("")){
                 enabled=false;
                    CombateStart.setEnabled(enabled);
                    CombateStart.setText("Pokemon No Encontrado:");
             }else{
                 CombateStart.setText("Pokemon Encontrado:");
                 enabled=true;
                 CombateStart.setEnabled(enabled);
             }
             //images
           String imagepath = "src/main/java/poo/assets/";
        if (selected_pokemon[0].length() == 1) {
            imagepath = imagepath + "00" + selected_pokemon[0] + ".png";
        } else if (selected_pokemon[0].length() == 2) {
            imagepath = imagepath + "0" + selected_pokemon[0] + ".png";
        } else if (selected_pokemon[0].length() == 3) {
            imagepath = imagepath + selected_pokemon[0] + ".png";
        }

        ImageIcon pic = new ImageIcon(imagepath);
        Image image = pic.getImage();
        Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
        pic = new ImageIcon(newimg);
        PokemonUserIMG.setIcon(pic);
        PokemonUserIMG.setOpaque(false);
             
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
    }
        
        
                public void readFileComplete(String search) {
        try {
            FileReader file_reader = new FileReader(list);
            BufferedReader buffered_reader = new BufferedReader(file_reader);
            String linea = "";
            String Text = "";
            while ((linea = buffered_reader.readLine()) != null) {
                String[] pokemon = linea.split(",");
                if (pokemon[1].contentEquals(search)) {
                    Text = Text + pokemon[1] + "\n";
                    selected_pokemon=pokemon;
                }
            }
             if(Text.equals("")){
                 enabled=false;
                    CombateStart.setEnabled(enabled);
                    CombateStart.setText("Pokemon No Encontrado:");
             }else{
                 CombateStart.setText("Pokemon Encontrado:");
                 enabled=true;
                 CombateStart.setEnabled(enabled);
             }
             //images
           String imagepath = "src/main/java/poo/assets/";
        if (selected_pokemon[0].length() == 1) {
            imagepath = imagepath + "00" + selected_pokemon[0] + ".png";
        } else if (selected_pokemon[0].length() == 2) {
            imagepath = imagepath + "0" + selected_pokemon[0] + ".png";
        } else if (selected_pokemon[0].length() == 3) {
            imagepath = imagepath + selected_pokemon[0] + ".png";
        }

        ImageIcon pic = new ImageIcon(imagepath);
        Image image = pic.getImage();
        Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
        pic = new ImageIcon(newimg);
        PokemonCpuIMG1.setIcon(pic);
        PokemonCpuIMG1.setOpaque(false);
             
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombateSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombateSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombateSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombateSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombateSetUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CombateStart;
    private javax.swing.JLabel PokemonCpuIMG1;
    private javax.swing.JTextField PokemonCpuRes;
    private javax.swing.JLabel PokemonUserIMG;
    private javax.swing.JTextField PokemonUserRes;
    private javax.swing.JButton buscarCpuButton;
    private javax.swing.JTextField buscarPokemonCpu;
    private javax.swing.JTextField buscarPokemonUser;
    private javax.swing.JButton buscarUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
