/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author noel
 */
public class Create extends javax.swing.JFrame {

    File file = new File("./pokemon_list.csv");
    String filename = "";
    String[] pokemon_Selected= {};
    boolean enabled=false;
    /**
     *
     * Creates new form Create
     */
    public Create() {
        initComponents();
         ImageIcon Img = new ImageIcon("src/main/java/poo/"+"Busqueda"+ ".jpg"); 
        Image image = Img.getImage();
        Image newimg = image.getScaledInstance(850, 510, java.awt.Image.SCALE_SMOOTH);
        Img = new ImageIcon(newimg);
        JLabel IMG = new JLabel (Img);
        IMG.setSize(700,450);
        IMG.setOpaque(false);
        add(IMG);
        IMG.setLocation(1, 1); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        search_results = new javax.swing.JTextArea();
        search_layout = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        select_this_pokemon = new javax.swing.JButton();
        search_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        search_results.setEditable(false);
        search_results.setColumns(20);
        search_results.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        search_results.setForeground(new java.awt.Color(0, 255, 0));
        search_results.setRows(2);
        search_results.setTabSize(4);
        search_results.setAutoscrolls(false);
        search_results.setEnabled(false);
        search_results.setFocusable(false);
        search_results.setRequestFocusEnabled(false);
        search_results.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(search_results);

        search_layout.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        search_layout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_layoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Busca tu Pokemon base: (presiona Enter para buscar)");

        select_this_pokemon.setText("Seleccionar");
        select_this_pokemon.setEnabled(false);
        select_this_pokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_this_pokemonActionPerformed(evt);
            }
        });

        search_status.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        search_status.setText("Pokemón Encontrado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(select_this_pokemon))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(search_status, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(search_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(search_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_this_pokemon)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_layoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_layoutActionPerformed
        // TODO add your handling code here:
        readFile();
    }//GEN-LAST:event_search_layoutActionPerformed

    private void select_this_pokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_this_pokemonActionPerformed
        // TODO add your handling code here:
            new Create_Pokemon(pokemon_Selected).setVisible(true);
    }//GEN-LAST:event_select_this_pokemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void readFile() {
        try {
            search_results.setText("");
            String nombre = search_layout.getText();
            FileReader file_reader = new FileReader(file);
            BufferedReader buffered_reader = new BufferedReader(file_reader);
            String linea = "";
            String Text = search_results.getText();
            while ((linea = buffered_reader.readLine()) != null) {
                String[] pokemon = linea.split(",");
                if (pokemon[1].contentEquals(nombre)) {
                    Text = Text + pokemon[1] + "\n";
                    pokemon_Selected=pokemon;
                }
            }
             if(Text.equals("")){
                 enabled=false;
                    select_this_pokemon.setEnabled(enabled);
                    search_status.setText("Pokemon No Encontrado:");
             }else{
                 search_status.setText("Pokemon Encontrado:");
                 enabled=true;
                 select_this_pokemon.setEnabled(enabled);
             }
            search_results.setText(Text);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_layout;
    private javax.swing.JTextArea search_results;
    private javax.swing.JLabel search_status;
    private javax.swing.JButton select_this_pokemon;
    // End of variables declaration//GEN-END:variables
}
